   apiVersion: apps/v1
   kind: Deployment
   metadata:
     name: mssql-deployment
     labels:
       app: mssql
   spec:
     replicas: 1 # You can increase this for high availability
     selector:
       matchLabels:
         app: mssql
     template:
       metadata:
         labels:
           app: mssql
       spec:
         containers:
           - name: mssql-container
             image: mcr.microsoft.com/mssql/server:2019-latest
             ports:
               - containerPort: 1433
             envFrom:
               - secretRef:
                   name: mssql-secret
             volumeMounts:
               - name: mssql-storage
                 mountPath: /var/opt/mssql
         volumes:
           - name: mssql-storage
             persistentVolumeClaim:
               claimName: mssql-pvc